services:
  web:
    build: .
    env_file:
      - .env
    container_name: aitproject_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated

  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: aitproject_sqlite_web
    volumes:
      - .database/trades.db:/data/trades.db:ro
    ports:
      - "8081:8080"
    command: >
      sqlite_web
        --host 0.0.0.0
        --port 8080
        /database/trades.db
